# Generated by Django 3.1.7 on 2021-03-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210309_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q10_opt1',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q10_opt2',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q10_opt3',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q10_opt4',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q10_qstn',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q1_opt1',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q1_opt2',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q1_opt3',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q1_opt4',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q1_qstn',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q2_opt1',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q2_opt2',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q2_opt3',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q2_opt4',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q2_qstn',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q3_opt1',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q3_opt2',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q3_opt3',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q3_opt4',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q3_qstn',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q4_opt1',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q4_opt2',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q4_opt3',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q4_opt4',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q4_qstn',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q5_opt1',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q5_opt2',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q5_opt3',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q5_opt4',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q5_qstn',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q6_opt1',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q6_opt2',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q6_opt3',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q6_opt4',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q6_qstn',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q7_opt1',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q7_opt2',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q7_opt3',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q7_opt4',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q7_qstn',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q8_opt1',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q8_opt2',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q8_opt3',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q8_opt4',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q8_qstn',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q9_opt1',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q9_opt2',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q9_opt3',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q9_opt4',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_q9_qstn',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
