# Generated by Django 3.1.7 on 2021-03-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210309_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_model',
            old_name='quiz_creator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='quiz_model',
            old_name='quiz_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='quiz_model',
            old_name='quiz_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='quiz_model',
            old_name='quiz_title',
            new_name='title',
        ),
    ]
