# Generated by Django 3.1.7 on 2021-02-23 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=127)),
                ('content', models.TextField(max_length=2549)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('op_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
