# Generated by Django 3.1.7 on 2021-03-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_post',
            old_name='content',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='user_post',
            old_name='date_time',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='user_post',
            old_name='subject',
            new_name='post_subject',
        ),
        migrations.RenameField(
            model_name='user_post',
            old_name='last_update',
            new_name='post_updated',
        ),
        migrations.RenameField(
            model_name='user_post',
            old_name='op_user',
            new_name='post_user',
        ),
    ]
