# Generated by Django 3.1.7 on 2021-03-09 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message_board', '0003_user_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Comment',
            fields=[
                ('cmnt_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmnt_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cmnt_details', models.TextField(max_length=1024)),
                ('cmnt_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
