# Generated by Django 3.1.7 on 2021-03-09 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0004_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_comment',
            old_name='cmnt_date_time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='user_comment',
            old_name='cmnt_details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='user_comment',
            old_name='cmnt_user',
            new_name='poster',
        ),
        migrations.AddField(
            model_name='user_comment',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='message_board.user_post'),
        ),
    ]
