# Generated by Django 3.1.7 on 2021-03-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0005_auto_20210309_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='post_tags',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='post_content',
            field=models.TextField(max_length=2048),
        ),
    ]
