# Generated by Django 3.1.7 on 2021-03-10 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0006_auto_20210310_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_comment',
            old_name='poster',
            new_name='cmnt_user',
        ),
    ]
