# Generated by Django 3.1.7 on 2021-03-10 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0007_auto_20210310_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_comment',
            old_name='details',
            new_name='cmnt_text',
        ),
        migrations.AlterField(
            model_name='user_comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='message_board.user_post'),
        ),
    ]
