# Generated by Django 3.1.7 on 2021-03-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0008_auto_20210310_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_comment',
            old_name='cmnt_text',
            new_name='comment',
        ),
    ]
