# Generated by Django 3.1.7 on 2021-03-10 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0009_auto_20210310_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
