# Generated by Django 3.1.6 on 2021-02-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('e_mail', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=30, null=True, unique=True)),
                ('user_type', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('A', 'Academic'), ('SN', 'Support Network')], max_length=2)),
            ],
        ),
    ]
